sudo: false

language:
  - python

python
  - 2.6
  - 2.7
  - 3.4
  - 3.5

install:
  - pip install -r requirements.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv src/tests_load_data.py --cov tests_network;
    else py.test -vv src/tests_load_data.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
email: false